name: Starter CI
on: [push, pull_request]
jobs: 
    frontend-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version-file: './frontend/.nvmrc'
            - name: "Install frontend dependencies"
              working-directory: ./frontend
              run: npm ci
            - name: "Build frontend"
              working-directory: ./frontend  
              run: npm run build

    backend-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '1.22'
            - name: Download Go dependencies
              working-directory: ./backend
              run: go mod download
            - name: Build backend
              working-directory: ./backend
              run: go build ./cmd/api/