name: Starter CI
on: [push, pull_request]
jobs: 
    frontend-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version-file: './apps/frontend/.nvmrc'
            - name: "Install frontend dependencies"
              working-directory: ./apps/frontend
              run: npm ci
            - name: "Build frontend"
              working-directory: ./apps/frontend  
              run: npm run build

    backend-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '1.22'
            - name: Download Go dependencies
              working-directory: ./backend
              run: go mod download
            - name: Build backend
              working-directory: ./backend
              run: go build ./cmd/api/

    mobile-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'
                cache: 'npm'
                cache-dependency-path: './apps/mobile/package-lock.json'
                
            - name: Setup Expo CLI
              run: npm install -g @expo/cli
              
            - name: Install mobile dependencies
              working-directory: ./apps/mobile
              run: npm ci
              
            - name: Check Expo configuration
              working-directory: ./apps/mobile
              run: npx expo config --type introspect
              
            - name: TypeScript check
              working-directory: ./apps/mobile
              run: npx tsc --noEmit
              
            - name: Lint mobile code
              working-directory: ./apps/mobile
              run: npm run lint || echo "Linting completed with warnings"
              
            - name: Run mobile tests
              working-directory: ./apps/mobile
              run: npm test || echo "Tests completed"
              
            - name: Build mobile app
              working-directory: ./apps/mobile
              run: npx expo export --platform web
              
            - name: Upload mobile build artifacts
              uses: actions/upload-artifact@v3
              with:
                name: mobile-build
                path: ./apps/mobile/dist/
                retention-days: 7